### ISSUE TITLE
Projektname fehlerhaft

### ISSUE THREAD

**Issue by dasdawidt** [Pereki/Dijkstra-Algorithm-Project-INF21#1]
Es fehlt ein k nach dem j. Der Algorithmus heißt "Dijkstra"

**Comment by dasdawidt** [comment]
Ordnername ist immer noch fehlerhaft :'(

**Comment by Pereki** [comment]
Danke für die Mitteilung, sorry für die späte Antwort, Problem ist schon gefixt
